// // Auto-generated 2026-05-16 from List_of_all_spells
// 389 items — regenerate: node scripts/scrape-bg3-icons.mjs
// Local copy — run scripts/download-bg3-icons.mjs to refresh
export const BG3_SPELL_MAP: Record<string, string> = {
  "acid splash": "/assets/icons/bg3/60px-Acid_Splash_Icon.webp",
  "blade ward": "/assets/icons/bg3/60px-Blade_Ward_Icon.webp",
  "bone chill": "/assets/icons/bg3/60px-Bone_Chill_Icon.webp",
  "booming blade": "/assets/icons/bg3/60px-Booming_Blade_Icon.webp",
  "bursting sinew": "/assets/icons/bg3/60px-Bursting_Sinew_Icon.webp",
  "dancing lights": "/assets/icons/bg3/60px-Dancing_Lights_Icon.webp",
  "eldritch blast": "/assets/icons/bg3/60px-Eldritch_Blast_Icon.webp",
  "fire bolt": "/assets/icons/bg3/60px-Fire_Bolt_Icon.webp",
  "friends": "/assets/icons/bg3/60px-Friends_Icon.webp",
  "guidance": "/assets/icons/bg3/60px-Guidance_Icon.webp",
  "light": "/assets/icons/bg3/60px-Light_Icon.webp",
  "mage hand": "/assets/icons/bg3/60px-Mage_Hand_Icon.webp",
  "minor illusion": "/assets/icons/bg3/60px-Minor_Illusion_Icon.webp",
  "poison spray": "/assets/icons/bg3/60px-Poison_Spray_Icon.webp",
  "produce flame": "/assets/icons/bg3/60px-Produce_Flame_Icon.webp",
  "ray of frost": "/assets/icons/bg3/60px-Ray_of_Frost_Icon.webp",
  "resistance": "/assets/icons/bg3/60px-Resistance_Cantrip_Icon.webp",
  "sacred flame": "/assets/icons/bg3/60px-Sacred_Flame_Icon.webp",
  "shillelagh": "/assets/icons/bg3/60px-Shillelagh_Icon.webp",
  "shocking grasp": "/assets/icons/bg3/60px-Shocking_Grasp_Icon.webp",
  "thaumaturgy": "/assets/icons/bg3/60px-Thaumaturgy_Icon.webp",
  "thorn whip": "/assets/icons/bg3/60px-Thorn_Whip_Icon.webp",
  "toll the dead": "/assets/icons/bg3/60px-Toll_the_Dead_Icon.webp",
  "true strike": "/assets/icons/bg3/60px-True_Strike_Icon.webp",
  "vicious mockery": "/assets/icons/bg3/60px-Vicious_Mockery_Icon.webp",
  "animal friendship": "/assets/icons/bg3/60px-Animal_Friendship_Icon.webp",
  "armour of agathys": "/assets/icons/bg3/60px-Armour_of_Agathys_Icon.webp",
  "arms of hadar": "/assets/icons/bg3/60px-Arms_of_Hadar_Icon.webp",
  "bane": "/assets/icons/bg3/60px-Bane_spell_Icon.webp",
  "bless": "/assets/icons/bg3/60px-Bless_Icon.webp",
  "burning hands": "/assets/icons/bg3/60px-Burning_Hands_Icon.webp",
  "charm person": "/assets/icons/bg3/60px-Charm_Person_Icon.webp",
  "chromatic orb": "/assets/icons/bg3/60px-Chromatic_Orb_Icon.webp",
  "colour spray": "/assets/icons/bg3/60px-Colour_Spray_Icon.webp",
  "command": "/assets/icons/bg3/60px-Command_Halt_Icon.webp",
  "compelled duel": "/assets/icons/bg3/60px-Compelled_Duel_Icon.webp",
  "create or destroy water": "/assets/icons/bg3/60px-Create_Water_Icon.webp",
  "cure wounds": "/assets/icons/bg3/60px-Cure_Wounds_Icon.webp",
  "disguise self": "/assets/icons/bg3/60px-Disguise_Self_Icon.webp",
  "dissonant whispers": "/assets/icons/bg3/60px-Dissonant_Whispers_Icon.webp",
  "divine favour": "/assets/icons/bg3/60px-Divine_Favour_Icon.webp",
  "enhance leap": "/assets/icons/bg3/60px-Enhance_Leap_Icon.webp",
  "ensnaring strike": "/assets/icons/bg3/60px-Ensnaring_Strike_Ranged_Icon.webp",
  "entangle": "/assets/icons/bg3/60px-Entangle_Icon.webp",
  "expeditious retreat": "/assets/icons/bg3/60px-Expeditious_Retreat_Icon.webp",
  "faerie fire": "/assets/icons/bg3/60px-Faerie_Fire_Icon.webp",
  "false life": "/assets/icons/bg3/60px-False_Life_Icon.webp",
  "feather fall": "/assets/icons/bg3/60px-Feather_Fall_Icon.webp",
  "find familiar": "/assets/icons/bg3/60px-Find_Familiar_Cat_Icon.webp",
  "fog cloud": "/assets/icons/bg3/60px-Fog_Cloud_Icon.webp",
  "goodberry": "/assets/icons/bg3/60px-Goodberry_Icon.webp",
  "grease": "/assets/icons/bg3/60px-Grease_Icon.webp",
  "guiding bolt": "/assets/icons/bg3/60px-Guiding_Bolt_Icon.webp",
  "hail of thorns": "/assets/icons/bg3/60px-Hail_of_Thorns_Icon.webp",
  "healing word": "/assets/icons/bg3/60px-Healing_Word_Icon.webp",
  "hellish rebuke": "/assets/icons/bg3/60px-Hellish_Rebuke_Icon.webp",
  "heroism": "/assets/icons/bg3/60px-Heroism_Icon.webp",
  "hex": "/assets/icons/bg3/60px-Hex_Icon.webp",
  "hunter's mark": "/assets/icons/bg3/60px-Hunter's_Mark_Icon.webp",
  "ice knife": "/assets/icons/bg3/60px-Ice_Knife_Icon.webp",
  "inflict wounds": "/assets/icons/bg3/60px-Inflict_Wounds_Icon.webp",
  "longstrider": "/assets/icons/bg3/60px-Longstrider_Icon.webp",
  "mage armour": "/assets/icons/bg3/60px-Mage_Armour_Icon.webp",
  "magic missile": "/assets/icons/bg3/60px-Magic_Missile_Icon.webp",
  "protection from evil and good": "/assets/icons/bg3/60px-Protection_from_Evil_and_Good_Icon.webp",
  "ray of sickness": "/assets/icons/bg3/60px-Ray_of_Sickness_Icon.webp",
  "sanctuary": "/assets/icons/bg3/60px-Sanctuary_Icon.webp",
  "searing smite": "/assets/icons/bg3/60px-Searing_Smite_Icon.webp",
  "shield": "/assets/icons/bg3/60px-Shield_spell_Icon.webp",
  "shield of faith": "/assets/icons/bg3/60px-Shield_of_Faith_Icon.webp",
  "sleep": "/assets/icons/bg3/60px-Sleep_Icon.webp",
  "speak with animals": "/assets/icons/bg3/60px-Speak_with_Animals_Icon.webp",
  "tasha's hideous laughter": "/assets/icons/bg3/60px-Tasha's_Hideous_Laughter_Icon.webp",
  "thunderous smite": "/assets/icons/bg3/60px-Thunderous_Smite_Icon.webp",
  "thunderwave": "/assets/icons/bg3/60px-Thunderwave_Icon.webp",
  "witch bolt": "/assets/icons/bg3/60px-Witch_Bolt_Icon.webp",
  "wrathful smite": "/assets/icons/bg3/60px-Wrathful_Smite_Icon.webp",
  "aid": "/assets/icons/bg3/60px-Aid_Icon.webp",
  "arcane lock": "/assets/icons/bg3/60px-Arcane_Lock_Icon.webp",
  "barkskin": "/assets/icons/bg3/60px-Barkskin_Icon.webp",
  "blindness": "/assets/icons/bg3/60px-Blindness_Icon.webp",
  "blur": "/assets/icons/bg3/60px-Blur_Icon.webp",
  "branding smite": "/assets/icons/bg3/60px-Branding_Smite_Melee_Icon.webp",
  "calm emotions": "/assets/icons/bg3/60px-Calm_Emotions_Icon.webp",
  "cloud of daggers": "/assets/icons/bg3/60px-Cloud_of_Daggers_Icon.webp",
  "crown of madness": "/assets/icons/bg3/60px-Crown_of_Madness_Icon.webp",
  "darkness": "/assets/icons/bg3/60px-Darkness_Icon.webp",
  "darkvision": "/assets/icons/bg3/60px-Darkvision_spell_Icon.webp",
  "detect thoughts": "/assets/icons/bg3/60px-Detect_Thoughts_Icon.webp",
  "enhance ability": "/assets/icons/bg3/60px-Enhance_Ability_Icon.webp",
  "enlarge/reduce": "/assets/icons/bg3/60px-Enlarge_Reduce_Icon.webp",
  "enthrall": "/assets/icons/bg3/60px-Enthrall_Icon.webp",
  "flame blade": "/assets/icons/bg3/60px-Flame_Blade_Icon.webp",
  "flaming sphere": "/assets/icons/bg3/60px-Flaming_Sphere_Icon.webp",
  "gust of wind": "/assets/icons/bg3/60px-Gust_of_Wind_Icon.webp",
  "heat metal": "/assets/icons/bg3/60px-Heat_Metal_Icon.webp",
  "hold person": "/assets/icons/bg3/60px-Hold_Person_Icon.webp",
  "invisibility": "/assets/icons/bg3/60px-Invisibility_spell_Icon.webp",
  "knock": "/assets/icons/bg3/60px-Knock_Icon.webp",
  "lesser restoration": "/assets/icons/bg3/60px-Lesser_Restoration_Icon.webp",
  "magic weapon": "/assets/icons/bg3/60px-Magic_Weapon_Icon.webp",
  "melf's acid arrow": "/assets/icons/bg3/60px-Melf's_Acid_Arrow_Icon.webp",
  "mirror image": "/assets/icons/bg3/60px-Mirror_Image_Icon.webp",
  "misty step": "/assets/icons/bg3/60px-Misty_Step_Icon.webp",
  "moonbeam": "/assets/icons/bg3/60px-Moonbeam_Icon.webp",
  "pass without trace": "/assets/icons/bg3/60px-Pass_Without_Trace_Icon.webp",
  "phantasmal force": "/assets/icons/bg3/60px-Phantasmal_Force_Icon.webp",
  "prayer of healing": "/assets/icons/bg3/60px-Prayer_of_Healing_Icon.webp",
  "protection from poison": "/assets/icons/bg3/60px-Protection_from_Poison_Icon.webp",
  "ray of enfeeblement": "/assets/icons/bg3/60px-Ray_of_Enfeeblement_Icon.webp",
  "scorching ray": "/assets/icons/bg3/60px-Scorching_Ray_Icon.webp",
  "see invisibility": "/assets/icons/bg3/60px-See_Invisibility_Icon.webp",
  "shadow blade": "/assets/icons/bg3/60px-Shadow_Blade_Icon.webp",
  "shatter": "/assets/icons/bg3/60px-Shatter_Icon.webp",
  "silence": "/assets/icons/bg3/60px-Silence_Icon.webp",
  "spike growth": "/assets/icons/bg3/60px-Spike_Growth_Icon.webp",
  "spiritual weapon": "/assets/icons/bg3/60px-Spiritual_Weapon_Icon.webp",
  "warding bond": "/assets/icons/bg3/60px-Warding_Bond_Icon.webp",
  "web": "/assets/icons/bg3/60px-Web_Icon.webp",
  "animate dead": "/assets/icons/bg3/60px-Animate_Dead_Icon.webp",
  "beacon of hope": "/assets/icons/bg3/60px-Beacon_of_Hope_Icon.webp",
  "bestow curse": "/assets/icons/bg3/60px-Bestow_Curse_Icon.webp",
  "blinding smite": "/assets/icons/bg3/60px-Blinding_Smite_Icon.webp",
  "blink": "/assets/icons/bg3/60px-Blink_Icon.webp",
  "call lightning": "/assets/icons/bg3/60px-Call_Lightning_Icon.webp",
  "conjure barrage": "/assets/icons/bg3/60px-Conjure_Barrage_Icon.webp",
  "counterspell": "/assets/icons/bg3/60px-Counterspell_Icon.webp",
  "crusader's mantle": "/assets/icons/bg3/60px-Crusader's_Mantle_Icon.webp",
  "daylight": "/assets/icons/bg3/60px-Daylight_Icon.webp",
  "elemental weapon": "/assets/icons/bg3/60px-Elemental_Weapon_Icon.webp",
  "fear": "/assets/icons/bg3/60px-Fear_Icon.webp",
  "feign death": "/assets/icons/bg3/60px-Feign_Death_Icon.webp",
  "fireball": "/assets/icons/bg3/60px-Fireball_Icon.webp",
  "gaseous form": "/assets/icons/bg3/60px-Gaseous_Form_Icon.webp",
  "glyph of warding": "/assets/icons/bg3/60px-Glyph_of_Warding_Icon.webp",
  "grant flight": "/assets/icons/bg3/60px-Grant_Flight_Icon.webp",
  "haste": "/assets/icons/bg3/60px-Haste_Icon.webp",
  "hunger of hadar": "/assets/icons/bg3/60px-Hunger_of_Hadar_Icon.webp",
  "hypnotic pattern": "/assets/icons/bg3/60px-Hypnotic_Pattern_Icon.webp",
  "lightning arrow": "/assets/icons/bg3/60px-Lightning_Arrow_Icon.webp",
  "lightning bolt": "/assets/icons/bg3/60px-Lightning_Bolt_Icon.webp",
  "mass healing word": "/assets/icons/bg3/60px-Mass_Healing_Word_Icon.webp",
  "plant growth": "/assets/icons/bg3/60px-Plant_Growth_Icon.webp",
  "protection from energy": "/assets/icons/bg3/60px-Protection_from_Energy_Icon.webp",
  "remove curse": "/assets/icons/bg3/60px-Remove_Curse_Icon.webp",
  "revivify": "/assets/icons/bg3/60px-Revivify_Icon.webp",
  "sleet storm": "/assets/icons/bg3/60px-Sleet_Storm_Icon.webp",
  "slow": "/assets/icons/bg3/60px-Slow_Icon.webp",
  "speak with dead": "/assets/icons/bg3/60px-Speak_with_Dead_Icon.webp",
  "spirit guardians": "/assets/icons/bg3/60px-Spirit_Guardians_Icon.webp",
  "stinking cloud": "/assets/icons/bg3/60px-Stinking_Cloud_Icon.webp",
  "vampiric touch": "/assets/icons/bg3/60px-Vampiric_Touch_Icon.webp",
  "warden of vitality": "/assets/icons/bg3/60px-Warden_of_Vitality_Icon.webp",
  "banishment": "/assets/icons/bg3/60px-Banishment_Icon.webp",
  "blight": "/assets/icons/bg3/60px-Blight_Icon.webp",
  "confusion": "/assets/icons/bg3/60px-Confusion_Icon.webp",
  "conjure minor elemental": "/assets/icons/bg3/60px-Conjure_Minor_Elemental_Azer_Icon.webp",
  "conjure woodland being": "/assets/icons/bg3/60px-Conjure_Woodland_Being_Icon.webp",
  "death ward": "/assets/icons/bg3/60px-Death_Ward_Icon.webp",
  "dimension door": "/assets/icons/bg3/60px-Dimension_Door_Icon.webp",
  "dominate beast": "/assets/icons/bg3/60px-Dominate_Beast_Icon.webp",
  "evard's black tentacles": "/assets/icons/bg3/60px-Evard's_Black_Tentacles_Icon.webp",
  "fire shield": "/assets/icons/bg3/60px-Fire_Shield_Icon.webp",
  "freedom of movement": "/assets/icons/bg3/60px-Freedom_of_Movement_Icon.webp",
  "grasping vine": "/assets/icons/bg3/60px-Grasping_Vine_Icon.webp",
  "greater invisibility": "/assets/icons/bg3/60px-Greater_Invisibility_Icon.webp",
  "guardian of faith": "/assets/icons/bg3/60px-Guardian_of_Faith_Icon.webp",
  "ice storm": "/assets/icons/bg3/60px-Ice_Storm_Icon.webp",
  "otiluke's resilient sphere": "/assets/icons/bg3/60px-Otiluke's_Resilient_Sphere_Icon.webp",
  "phantasmal killer": "/assets/icons/bg3/60px-Phantasmal_Killer_Icon.webp",
  "polymorph": "/assets/icons/bg3/60px-Polymorph_Icon.webp",
  "staggering smite": "/assets/icons/bg3/60px-Staggering_Smite_Icon.webp",
  "stoneskin": "/assets/icons/bg3/60px-Stoneskin_Icon.webp",
  "wall of fire": "/assets/icons/bg3/60px-Wall_of_Fire_Icon.webp",
  "banishing smite": "/assets/icons/bg3/60px-Banishing_Smite_Melee_Icon.webp",
  "cloudkill": "/assets/icons/bg3/60px-Cloudkill_Icon.webp",
  "cone of cold": "/assets/icons/bg3/60px-Cone_of_Cold_Icon.webp",
  "conjure elemental": "/assets/icons/bg3/60px-Conjure_Elemental_Icon.webp",
  "contagion": "/assets/icons/bg3/60px-Contagion_Filth_Fever_Icon.webp",
  "curriculum of strategy: artistry of war": "/assets/icons/bg3/60px-Curriculum_of_Strategy_Artistry_of_War_Icon.webp",
  "destructive wave": "/assets/icons/bg3/60px-Destructive_Wave_Icon.webp",
  "dethrone": "/assets/icons/bg3/60px-Dethrone_Icon.webp",
  "dispel evil and good": "/assets/icons/bg3/60px-Dispel_Evil_And_Good_Icon.webp",
  "dominate person": "/assets/icons/bg3/60px-Dominate_Person_Icon.webp",
  "flame strike": "/assets/icons/bg3/60px-Flame_Strike_Icon.webp",
  "greater restoration": "/assets/icons/bg3/60px-Greater_Restoration_Icon.webp",
  "hold monster": "/assets/icons/bg3/60px-Hold_Monster_Icon.webp",
  "insect plague": "/assets/icons/bg3/60px-Insect_Plague_Icon.webp",
  "mass cure wounds": "/assets/icons/bg3/60px-Mass_Cure_Wounds_Icon.webp",
  "planar binding": "/assets/icons/bg3/60px-Planar_Binding_Icon.webp",
  "seeming": "/assets/icons/bg3/60px-Seeming_Icon.webp",
  "telekinesis": "/assets/icons/bg3/60px-Telekinesis_Icon.webp",
  "wall of stone": "/assets/icons/bg3/60px-Wall_of_Stone_Icon.webp",
  "arcane gate": "/assets/icons/bg3/60px-Arcane_Gate_Icon.webp",
  "blade barrier": "/assets/icons/bg3/60px-Blade_Barrier_Icon.webp",
  "chain lightning": "/assets/icons/bg3/60px-Chain_Lightning_Icon.webp",
  "circle of death": "/assets/icons/bg3/60px-Circle_of_Death_Icon.webp",
  "create undead": "/assets/icons/bg3/60px-Create_Undead_Icon.webp",
  "disintegrate": "/assets/icons/bg3/60px-Disintegrate_Icon.webp",
  "eyebite": "/assets/icons/bg3/60px-Eyebite_Panicked_Icon.webp",
  "flesh to stone": "/assets/icons/bg3/60px-Flesh_to_Stone_Icon.webp",
  "globe of invulnerability": "/assets/icons/bg3/60px-Globe_of_Invulnerability_Icon.webp",
  "harm": "/assets/icons/bg3/60px-Harm_Icon.webp",
  "heal": "/assets/icons/bg3/60px-Heal_Icon.webp",
  "heroes' feast": "/assets/icons/bg3/60px-Heroes'_Feast_Icon.webp",
  "otiluke's freezing sphere": "/assets/icons/bg3/60px-Otiluke's_Freezing_Sphere_Icon.webp",
  "otto's irresistible dance": "/assets/icons/bg3/60px-Otto's_Irresistible_Dance_Icon.webp",
  "planar ally": "/assets/icons/bg3/60px-Planar_Ally_Icon.webp",
  "sights of the seelie: summon deva": "/assets/icons/bg3/60px-Sights_of_the_Seelie_Summon_Deva_Icon.webp",
  "sunbeam": "/assets/icons/bg3/60px-Sunbeam_Icon.webp",
  "wall of ice": "/assets/icons/bg3/60px-Wall_of_Ice_Icon.webp",
  "wall of thorns": "/assets/icons/bg3/60px-Wall_of_Thorns_Icon.webp",
  "wind walk": "/assets/icons/bg3/60px-Wind_Walk_Icon.webp",
  "bhaal's power word kill ritual": "/assets/icons/bg3/60px-Power_Word_Kill_Icon.webp",
  "power word kill": "/assets/icons/bg3/60px-Power_Word_Kill_Icon.webp",
  "karsus' compulsion": "/assets/icons/bg3/60px-Karsus'_Compulsion_Icon.webp",
  "formsculpt: tressym": "/assets/icons/bg3/60px-Formsculpt_Tressym_Icon.webp",
  "power word: ruin": "/assets/icons/bg3/60px-Power_Word_Ruin_Icon.webp",
  "divine revelry": "/assets/icons/bg3/60px-Divine_Revelry_Icon.webp",
  "elemental retort": "/assets/icons/bg3/60px-Generic_Damage_Icon.webp",
  "finger of death": "/assets/icons/bg3/60px-Generic_Death_Icon.webp",
  "hellfire orb": "/assets/icons/bg3/60px-Fireball_Icon.webp",
  "incinerate": "/assets/icons/bg3/60px-Flame_Strike_Icon.webp",
  "keeper's fee": "/assets/icons/bg3/60px-Generic_Control_Icon.webp",
  "lunar smite": "/assets/icons/bg3/60px-Lunar_Smite_Icon.webp",
  "lovely assistant": "/assets/icons/bg3/60px-Animate_Dead_Zombie_Icon.webp",
  "mind spike": "/assets/icons/bg3/60px-Mind_Spike_Icon.webp",
  "possession": "/assets/icons/bg3/60px-Generic_Control_Icon.webp",
  "promise of wealth": "/assets/icons/bg3/60px-Generic_Control_Icon.webp",
  "revoke guest status": "/assets/icons/bg3/60px-Banishment_Icon.webp",
  "shield of screams": "/assets/icons/bg3/60px-Generic_Control_Icon.webp",
  "summon gilded hellsboar": "/assets/icons/bg3/60px-Find_Familiar_Cat_Icon.webp",
  "teleport to submersible": "/assets/icons/bg3/60px-Teleport_to_Submersible_Icon.webp",
  "the closed fist of bane": "/assets/icons/bg3/60px-Generic_Explosion_Icon.webp",
  "tyrant's bindings": "/assets/icons/bg3/60px-Generic_Control_Icon.webp",
  "beckoning darkness": "/assets/icons/bg3/60px-Generic_Darkness_Icon.webp",
  "brand the weak": "/assets/icons/bg3/60px-Brand_the_Weak_Icon.webp",
  "challenge to duel": "/assets/icons/bg3/60px-Compelled_Duel_Icon.webp",
  "danse macabre": "/assets/icons/bg3/60px-Danse_Macabre_Icon.webp",
  "draconic elemental weapon": "/assets/icons/bg3/60px-Elemental_Weapon_Icon.webp",
  "elemental age": "/assets/icons/bg3/60px-Elemental_Weapon_Icon.webp",
  "ensnaring strands": "/assets/icons/bg3/60px-Ensnaring_Strands_Icon.webp",
  "exhort the risen": "/assets/icons/bg3/60px-Command_Halt_Undead_Icon.webp",
  "find familiar: cheeky quasit": "/assets/icons/bg3/60px-Find_Familiar_Quasit_Icon.webp",
  "flesh to gold": "/assets/icons/bg3/60px-Flesh_to_Gold_Icon.webp",
  "howl of the dead": "/assets/icons/bg3/60px-Howl_of_the_Dead_Icon.webp",
  "kereska's favour": "/assets/icons/bg3/60px-Protection_from_Energy_Icon.webp",
  "khalid's gift: aid": "/assets/icons/bg3/60px-Aid_Icon.webp",
  "paralyzing ray": "/assets/icons/bg3/60px-Generic_Damage_Icon.webp",
  "protection from missiles": "/assets/icons/bg3/60px-Protection_from_Missiles_Icon.webp",
  "ray of fear": "/assets/icons/bg3/60px-Generic_Control_Icon.webp",
  "ride the winds": "/assets/icons/bg3/60px-Gaseous_Form_Icon.webp",
  "selûne's dream": "/assets/icons/bg3/60px-Selûne's_Dream_Icon.webp",
  "shar's aegis": "/assets/icons/bg3/60px-Shield_of_Faith_Icon.webp",
  "summon quothe the raven": "/assets/icons/bg3/60px-Find_Familiar_Raven_Icon.webp",
  "wounding ray": "/assets/icons/bg3/60px-Generic_Necrotic_Icon.webp",
  "actions": "/assets/icons/bg3/30px-Action_Icon.png.webp",
  "initiative": "/assets/icons/bg3/30px-Initiative_Icon.png.webp",
  "movement speed": "/assets/icons/bg3/Movement_Speed_Icon.png",
  "resources": "/assets/icons/bg3/30px-Bonus_Action_Icon.png.webp",
  "abilities": "/assets/icons/bg3/30px-Abilities_Icon.png.webp",
  "advantage": "/assets/icons/bg3/30px-Advantage_Icon.png.webp",
  "attacks": "/assets/icons/bg3/30px-Attack_Save.png.webp",
  "concentration": "/assets/icons/bg3/30px-Concentration_Icon.png.webp",
  "damage": "/assets/icons/bg3/30px-1d4_+_1d6_Poison.png.webp",
  "healing": "/assets/icons/bg3/30px-Healing_Icon.png.webp",
  "inspiration": "/assets/icons/bg3/30px-Inspiration_Icon.png.webp",
  "saving throw": "/assets/icons/bg3/30px-Saving_Throw_Icon.png.webp",
  "alchemy": "/assets/icons/bg3/30px-Alchemy_Icon.png.webp",
  "approval": "/assets/icons/bg3/30px-Attitude_Yellow_Wiki_Icon.png.webp",
  "barter": "/assets/icons/bg3/30px-Gold_Icon.png.webp",
  "attitude": "/assets/icons/bg3/21px-Attitude_Green_UI_Icon.png.webp",
  "resting": "/assets/icons/bg3/30px-Camp_Supplies_Icon.png.webp",
  "clouds": "/assets/icons/bg3/30px-Fog_cloud_Icon.webp",
  "difficult terrain": "/assets/icons/bg3/30px-Difficult_Terrain_Condition_Icon.webp",
  "obscurity": "/assets/icons/bg3/30px-Lightly_Obscured_Condition_Icon.webp",
  "sight": "/assets/icons/bg3/30px-Clear_Area_Condition_Icon.webp",
  "surfaces": "/assets/icons/bg3/30px-Acid_surface_Icon.webp",
  "amulets": "/assets/icons/bg3/38px-Amulets_Icon.png.webp",
  "armour": "/assets/icons/bg3/38px-Armour_Icon.png.webp",
  "cloaks": "/assets/icons/bg3/38px-Cloaks_Icon.png.webp",
  "clothing": "/assets/icons/bg3/38px-Clothing_Icon.png.webp",
  "footwear": "/assets/icons/bg3/38px-Boots_Icon.png.webp",
  "handwear": "/assets/icons/bg3/38px-Gloves_Icon.png.webp",
  "headwear": "/assets/icons/bg3/38px-Helmets_Icon.png.webp",
  "light sources": "/assets/icons/bg3/38px-Light_Sources_Icon.png.webp",
  "musical instruments": "/assets/icons/bg3/38px-Musical_Instruments_Icon.png.webp",
  "rings": "/assets/icons/bg3/38px-Rings_Icon.png.webp",
  "shields": "/assets/icons/bg3/38px-Shields_Icon.png.webp",
  "weapons": "/assets/icons/bg3/Weapons_Icon.png",
  "consumables": "/assets/icons/bg3/30px-Consumables_Icon.png.webp",
  "containers": "/assets/icons/bg3/30px-Backpack_A_Unfaded.png.webp",
  "miscellaneous": "/assets/icons/bg3/30px-Fishing_Rod_Unfaded.png.webp",
  "charisma": "/assets/icons/bg3/30px-Charisma_Small_Icon.png.webp",
  "constitution": "/assets/icons/bg3/30px-Constitution_Small_Icon.png.webp",
  "dexterity": "/assets/icons/bg3/30px-Dexterity_Small_Icon.png.webp",
  "intelligence": "/assets/icons/bg3/30px-Intelligence_Small_Icon.png.webp",
  "strength": "/assets/icons/bg3/30px-Strength_Small_Icon.png.webp",
  "wisdom": "/assets/icons/bg3/30px-Wisdom_Small_Icon.png.webp",
  "acrobatics": "/assets/icons/bg3/30px-Acrobatics_Icon.png.webp",
  "animal handling": "/assets/icons/bg3/30px-Animal_Handling_Icon.png.webp",
  "arcana": "/assets/icons/bg3/30px-Arcana_Icon.png.webp",
  "athletics": "/assets/icons/bg3/30px-Athletics_Icon.png.webp",
  "deception": "/assets/icons/bg3/30px-Deception_Icon.png.webp",
  "history": "/assets/icons/bg3/30px-History_Icon.png.webp",
  "insight": "/assets/icons/bg3/30px-Insight_Icon.png.webp",
  "intimidation": "/assets/icons/bg3/30px-Intimidation_Icon.png.webp",
  "investigation": "/assets/icons/bg3/30px-Investigation_Icon.png.webp",
  "medicine": "/assets/icons/bg3/30px-Medicine_Icon.png.webp",
  "nature": "/assets/icons/bg3/30px-Nature_Icon.png.webp",
  "perception": "/assets/icons/bg3/30px-Perception_Icon.png.webp",
  "performance": "/assets/icons/bg3/30px-Performance_Icon.png.webp",
  "persuasion": "/assets/icons/bg3/30px-Persuasion_Icon.png.webp",
  "religion": "/assets/icons/bg3/30px-Religion_Icon.png.webp",
  "sleight of hand": "/assets/icons/bg3/30px-Sleight_of_Hand_Icon.png.webp",
  "stealth": "/assets/icons/bg3/30px-Stealth_Icon.png.webp",
  "survival": "/assets/icons/bg3/30px-Survival_Icon.png.webp",
  "conditions": "/assets/icons/bg3/30px-Feat_CC_Icon.png.webp",
  "feats": "/assets/icons/bg3/30px-Feat_CC_Icon.png.webp",
  "illithid powers": "/assets/icons/bg3/30px-Illithid_Power_Icon.png.webp",
  "passives": "/assets/icons/bg3/30px-Feat_CC_Icon.png.webp",
  "permanent bonuses": "/assets/icons/bg3/30px-Loviatar's_Love_Condition_Icon.webp",
  "spells": "/assets/icons/bg3/30px-Prepared_Spells_Icon.webp",
  "armour class": "/assets/icons/bg3/30px-Armour_Class_Icon.png.webp",
  "creature sizes": "/assets/icons/bg3/30px-Creature_Size_Icon.png.webp",
  "creature types": "/assets/icons/bg3/30px-Creature_Type_Icon.png.webp",
  "hit points": "/assets/icons/bg3/30px-HP_Icon.png.webp",
  "experience": "/assets/icons/bg3/30px-Level_up_icon.webp",
  "point buy": "/assets/icons/bg3/SpellSubSelectIndicator.png",
  "proficiency": "/assets/icons/bg3/27px-Proficiency_Icon.png.webp",
  "resistances": "/assets/icons/bg3/20px-Bludgeoning_Resistance_Full.png.webp",
  "barbarian": "/assets/icons/bg3/30px-Barbarian_Icon_Small.webp",
  "bard": "/assets/icons/bg3/30px-Class_Bard_Hotbar_Icon.png.webp",
  "cleric": "/assets/icons/bg3/30px-Class_Cleric_Hotbar_Icon.png.webp",
  "druid": "/assets/icons/bg3/30px-Class_Druid_Hotbar_Icon.png.webp",
  "fighter": "/assets/icons/bg3/30px-Class_Fighter_Hotbar_Icon.png.webp",
  "monk": "/assets/icons/bg3/30px-Monk_Icon_Small.webp",
  "paladin": "/assets/icons/bg3/30px-Class_Paladin_Hotbar_Icon.png.webp",
  "ranger": "/assets/icons/bg3/30px-Class_Ranger_Hotbar_Icon.png.webp",
  "rogue": "/assets/icons/bg3/30px-Class_Rogue_Hotbar_Icon.png.webp",
  "sorcerer": "/assets/icons/bg3/30px-Class_Sorcerer_Hotbar_Icon.png.webp",
  "warlock": "/assets/icons/bg3/30px-Class_Warlock_Hotbar_Icon.png.webp",
  "wizard": "/assets/icons/bg3/30px-Class_Wizard_Hotbar_Icon.png.webp",
  "acolyte": "/assets/icons/bg3/30px-Background_Acolyte_Icon.png.webp",
  "charlatan": "/assets/icons/bg3/30px-Background_Charlatan_Icon.png.webp",
  "criminal": "/assets/icons/bg3/30px-Background_Criminal_Icon.png.webp",
  "entertainer": "/assets/icons/bg3/30px-Background_Entertainer_Icon.png.webp",
  "folk hero": "/assets/icons/bg3/30px-Background_Folk_Hero_Icon.png.webp",
  "guild artisan": "/assets/icons/bg3/30px-Background_Guild_Artisan_Icon.png.webp",
  "haunted one": "/assets/icons/bg3/30px-Background_Haunted_One_Icon.png.webp",
  "noble": "/assets/icons/bg3/30px-Background_Noble_Icon.png.webp",
  "outlander": "/assets/icons/bg3/30px-Background_Outlander_Icon.png.webp",
  "sage": "/assets/icons/bg3/30px-Background_Sage_Icon.png.webp",
  "soldier": "/assets/icons/bg3/30px-Background_Soldier_Icon.png.webp",
  "urchin": "/assets/icons/bg3/30px-Background_Urchin_Icon.png.webp",
  "dragonborn": "/assets/icons/bg3/30px-Race_Dragonborn.png.webp",
  "drow": "/assets/icons/bg3/30px-Race_Drow.png.webp",
  "dwarf": "/assets/icons/bg3/30px-Race_Dwarf.png.webp",
  "elf": "/assets/icons/bg3/30px-Race_Elf.png.webp",
  "githyanki": "/assets/icons/bg3/30px-Race_Githyanki.png.webp",
  "gnome": "/assets/icons/bg3/30px-Race_Gnome.png.webp",
  "half-elf": "/assets/icons/bg3/30px-Race_Half-Elf.png.webp",
  "half-orc": "/assets/icons/bg3/30px-Race_Half-Orc.png.webp",
  "halfling": "/assets/icons/bg3/30px-Race_Halfling.png.webp",
  "human": "/assets/icons/bg3/30px-Race_Human.png.webp",
  "tiefling": "/assets/icons/bg3/30px-Race_Tiefling.png.webp",
  "bahamut": "/assets/icons/bg3/30px-Bahamut_Icon.png.webp",
  "corellon larethian": "/assets/icons/bg3/30px-Corellon_Larethian_Icon.png.webp",
  "eilistraee": "/assets/icons/bg3/30px-Eilistraee_Icon.png.webp",
  "garl glittergold": "/assets/icons/bg3/30px-Garl_Glittergold_Icon.png.webp",
  "gruumsh": "/assets/icons/bg3/30px-Gruumsh_Icon.png.webp",
  "helm": "/assets/icons/bg3/30px-Helm_Icon.png.webp",
  "ilmater": "/assets/icons/bg3/30px-Ilmater_Icon.png.webp",
  "laduguer": "/assets/icons/bg3/30px-Laduguer_Icon.png.webp",
  "lathander": "/assets/icons/bg3/30px-Lathander_Icon.png.webp",
  "lolth": "/assets/icons/bg3/30px-Lolth_Icon.png.webp",
  "kelemvor": "/assets/icons/bg3/30px-Kelemvor_Icon.png.webp",
  "mielikki": "/assets/icons/bg3/30px-Mielikki_Icon.png.webp",
  "moradin": "/assets/icons/bg3/30px-Moradin_Icon.png.webp",
  "mystra": "/assets/icons/bg3/30px-Mystra_Icon.png.webp",
  "oghma": "/assets/icons/bg3/30px-Oghma_Icon.png.webp",
  "selûne": "/assets/icons/bg3/30px-Selune_Icon.png.webp",
  "shar": "/assets/icons/bg3/30px-Shar_Icon.png.webp",
  "talos": "/assets/icons/bg3/30px-Talos_Icon.png.webp",
  "tempus": "/assets/icons/bg3/30px-Tempus_Icon.png.webp",
  "tiamat": "/assets/icons/bg3/30px-Tiamat_Icon.png.webp",
  "tyr": "/assets/icons/bg3/30px-Tyr_Icon.png.webp",
  "vlaakith": "/assets/icons/bg3/30px-Vlaakith_Icon.png.webp",
  "yondalla": "/assets/icons/bg3/30px-Yondalla_Icon.png.webp",
}