/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSpellbookRouteImport } from './routes/_authenticated/spellbook'
import { Route as AuthenticatedBestiaryRouteImport } from './routes/_authenticated/bestiary'
import { Route as AuthenticatedJoinCampaignIdRouteImport } from './routes/_authenticated/join/$campaignId'
import { Route as AuthenticatedCharactersNewRouteImport } from './routes/_authenticated/characters/new'
import { Route as AuthenticatedCharactersCharacterIdRouteImport } from './routes/_authenticated/characters/$characterId'
import { Route as AuthenticatedCampaignsNewRouteImport } from './routes/_authenticated/campaigns/new'
import { Route as AuthenticatedCampaignsCampaignIdRouteImport } from './routes/_authenticated/campaigns/$campaignId'
import { Route as AuthenticatedCampaignsCampaignIdIndexRouteImport } from './routes/_authenticated/campaigns/$campaignId.index'
import { Route as AuthenticatedCampaignsCampaignIdTabernaRouteImport } from './routes/_authenticated/campaigns/$campaignId.taberna'
import { Route as AuthenticatedCampaignsCampaignIdPnjRouteImport } from './routes/_authenticated/campaigns/$campaignId.pnj'
import { Route as AuthenticatedCampaignsCampaignIdObjetosRouteImport } from './routes/_authenticated/campaigns/$campaignId.objetos'
import { Route as AuthenticatedCampaignsCampaignIdMapasRouteImport } from './routes/_authenticated/campaigns/$campaignId.mapas'
import { Route as AuthenticatedCampaignsCampaignIdLuchaRouteImport } from './routes/_authenticated/campaigns/$campaignId.lucha'
import { Route as AuthenticatedCampaignsCampaignIdHechizosRouteImport } from './routes/_authenticated/campaigns/$campaignId.hechizos'
import { Route as AuthenticatedCampaignsCampaignIdHabilidadesRouteImport } from './routes/_authenticated/campaigns/$campaignId.habilidades'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSpellbookRoute = AuthenticatedSpellbookRouteImport.update({
  id: '/spellbook',
  path: '/spellbook',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBestiaryRoute = AuthenticatedBestiaryRouteImport.update({
  id: '/bestiary',
  path: '/bestiary',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJoinCampaignIdRoute =
  AuthenticatedJoinCampaignIdRouteImport.update({
    id: '/join/$campaignId',
    path: '/join/$campaignId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCharactersNewRoute =
  AuthenticatedCharactersNewRouteImport.update({
    id: '/characters/new',
    path: '/characters/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCharactersCharacterIdRoute =
  AuthenticatedCharactersCharacterIdRouteImport.update({
    id: '/characters/$characterId',
    path: '/characters/$characterId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignsNewRoute =
  AuthenticatedCampaignsNewRouteImport.update({
    id: '/campaigns/new',
    path: '/campaigns/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignsCampaignIdRoute =
  AuthenticatedCampaignsCampaignIdRouteImport.update({
    id: '/campaigns/$campaignId',
    path: '/campaigns/$campaignId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignsCampaignIdIndexRoute =
  AuthenticatedCampaignsCampaignIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCampaignsCampaignIdRoute,
  } as any)
const AuthenticatedCampaignsCampaignIdTabernaRoute =
  AuthenticatedCampaignsCampaignIdTabernaRouteImport.update({
    id: '/taberna',
    path: '/taberna',
    getParentRoute: () => AuthenticatedCampaignsCampaignIdRoute,
  } as any)
const AuthenticatedCampaignsCampaignIdPnjRoute =
  AuthenticatedCampaignsCampaignIdPnjRouteImport.update({
    id: '/pnj',
    path: '/pnj',
    getParentRoute: () => AuthenticatedCampaignsCampaignIdRoute,
  } as any)
const AuthenticatedCampaignsCampaignIdObjetosRoute =
  AuthenticatedCampaignsCampaignIdObjetosRouteImport.update({
    id: '/objetos',
    path: '/objetos',
    getParentRoute: () => AuthenticatedCampaignsCampaignIdRoute,
  } as any)
const AuthenticatedCampaignsCampaignIdMapasRoute =
  AuthenticatedCampaignsCampaignIdMapasRouteImport.update({
    id: '/mapas',
    path: '/mapas',
    getParentRoute: () => AuthenticatedCampaignsCampaignIdRoute,
  } as any)
const AuthenticatedCampaignsCampaignIdLuchaRoute =
  AuthenticatedCampaignsCampaignIdLuchaRouteImport.update({
    id: '/lucha',
    path: '/lucha',
    getParentRoute: () => AuthenticatedCampaignsCampaignIdRoute,
  } as any)
const AuthenticatedCampaignsCampaignIdHechizosRoute =
  AuthenticatedCampaignsCampaignIdHechizosRouteImport.update({
    id: '/hechizos',
    path: '/hechizos',
    getParentRoute: () => AuthenticatedCampaignsCampaignIdRoute,
  } as any)
const AuthenticatedCampaignsCampaignIdHabilidadesRoute =
  AuthenticatedCampaignsCampaignIdHabilidadesRouteImport.update({
    id: '/habilidades',
    path: '/habilidades',
    getParentRoute: () => AuthenticatedCampaignsCampaignIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/bestiary': typeof AuthenticatedBestiaryRoute
  '/spellbook': typeof AuthenticatedSpellbookRoute
  '/campaigns/$campaignId': typeof AuthenticatedCampaignsCampaignIdRouteWithChildren
  '/campaigns/new': typeof AuthenticatedCampaignsNewRoute
  '/characters/$characterId': typeof AuthenticatedCharactersCharacterIdRoute
  '/characters/new': typeof AuthenticatedCharactersNewRoute
  '/join/$campaignId': typeof AuthenticatedJoinCampaignIdRoute
  '/campaigns/$campaignId/habilidades': typeof AuthenticatedCampaignsCampaignIdHabilidadesRoute
  '/campaigns/$campaignId/hechizos': typeof AuthenticatedCampaignsCampaignIdHechizosRoute
  '/campaigns/$campaignId/lucha': typeof AuthenticatedCampaignsCampaignIdLuchaRoute
  '/campaigns/$campaignId/mapas': typeof AuthenticatedCampaignsCampaignIdMapasRoute
  '/campaigns/$campaignId/objetos': typeof AuthenticatedCampaignsCampaignIdObjetosRoute
  '/campaigns/$campaignId/pnj': typeof AuthenticatedCampaignsCampaignIdPnjRoute
  '/campaigns/$campaignId/taberna': typeof AuthenticatedCampaignsCampaignIdTabernaRoute
  '/campaigns/$campaignId/': typeof AuthenticatedCampaignsCampaignIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/bestiary': typeof AuthenticatedBestiaryRoute
  '/spellbook': typeof AuthenticatedSpellbookRoute
  '/': typeof AuthenticatedIndexRoute
  '/campaigns/new': typeof AuthenticatedCampaignsNewRoute
  '/characters/$characterId': typeof AuthenticatedCharactersCharacterIdRoute
  '/characters/new': typeof AuthenticatedCharactersNewRoute
  '/join/$campaignId': typeof AuthenticatedJoinCampaignIdRoute
  '/campaigns/$campaignId/habilidades': typeof AuthenticatedCampaignsCampaignIdHabilidadesRoute
  '/campaigns/$campaignId/hechizos': typeof AuthenticatedCampaignsCampaignIdHechizosRoute
  '/campaigns/$campaignId/lucha': typeof AuthenticatedCampaignsCampaignIdLuchaRoute
  '/campaigns/$campaignId/mapas': typeof AuthenticatedCampaignsCampaignIdMapasRoute
  '/campaigns/$campaignId/objetos': typeof AuthenticatedCampaignsCampaignIdObjetosRoute
  '/campaigns/$campaignId/pnj': typeof AuthenticatedCampaignsCampaignIdPnjRoute
  '/campaigns/$campaignId/taberna': typeof AuthenticatedCampaignsCampaignIdTabernaRoute
  '/campaigns/$campaignId': typeof AuthenticatedCampaignsCampaignIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/bestiary': typeof AuthenticatedBestiaryRoute
  '/_authenticated/spellbook': typeof AuthenticatedSpellbookRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/campaigns/$campaignId': typeof AuthenticatedCampaignsCampaignIdRouteWithChildren
  '/_authenticated/campaigns/new': typeof AuthenticatedCampaignsNewRoute
  '/_authenticated/characters/$characterId': typeof AuthenticatedCharactersCharacterIdRoute
  '/_authenticated/characters/new': typeof AuthenticatedCharactersNewRoute
  '/_authenticated/join/$campaignId': typeof AuthenticatedJoinCampaignIdRoute
  '/_authenticated/campaigns/$campaignId/habilidades': typeof AuthenticatedCampaignsCampaignIdHabilidadesRoute
  '/_authenticated/campaigns/$campaignId/hechizos': typeof AuthenticatedCampaignsCampaignIdHechizosRoute
  '/_authenticated/campaigns/$campaignId/lucha': typeof AuthenticatedCampaignsCampaignIdLuchaRoute
  '/_authenticated/campaigns/$campaignId/mapas': typeof AuthenticatedCampaignsCampaignIdMapasRoute
  '/_authenticated/campaigns/$campaignId/objetos': typeof AuthenticatedCampaignsCampaignIdObjetosRoute
  '/_authenticated/campaigns/$campaignId/pnj': typeof AuthenticatedCampaignsCampaignIdPnjRoute
  '/_authenticated/campaigns/$campaignId/taberna': typeof AuthenticatedCampaignsCampaignIdTabernaRoute
  '/_authenticated/campaigns/$campaignId/': typeof AuthenticatedCampaignsCampaignIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/bestiary'
    | '/spellbook'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/characters/$characterId'
    | '/characters/new'
    | '/join/$campaignId'
    | '/campaigns/$campaignId/habilidades'
    | '/campaigns/$campaignId/hechizos'
    | '/campaigns/$campaignId/lucha'
    | '/campaigns/$campaignId/mapas'
    | '/campaigns/$campaignId/objetos'
    | '/campaigns/$campaignId/pnj'
    | '/campaigns/$campaignId/taberna'
    | '/campaigns/$campaignId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/bestiary'
    | '/spellbook'
    | '/'
    | '/campaigns/new'
    | '/characters/$characterId'
    | '/characters/new'
    | '/join/$campaignId'
    | '/campaigns/$campaignId/habilidades'
    | '/campaigns/$campaignId/hechizos'
    | '/campaigns/$campaignId/lucha'
    | '/campaigns/$campaignId/mapas'
    | '/campaigns/$campaignId/objetos'
    | '/campaigns/$campaignId/pnj'
    | '/campaigns/$campaignId/taberna'
    | '/campaigns/$campaignId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/_authenticated/bestiary'
    | '/_authenticated/spellbook'
    | '/_authenticated/'
    | '/_authenticated/campaigns/$campaignId'
    | '/_authenticated/campaigns/new'
    | '/_authenticated/characters/$characterId'
    | '/_authenticated/characters/new'
    | '/_authenticated/join/$campaignId'
    | '/_authenticated/campaigns/$campaignId/habilidades'
    | '/_authenticated/campaigns/$campaignId/hechizos'
    | '/_authenticated/campaigns/$campaignId/lucha'
    | '/_authenticated/campaigns/$campaignId/mapas'
    | '/_authenticated/campaigns/$campaignId/objetos'
    | '/_authenticated/campaigns/$campaignId/pnj'
    | '/_authenticated/campaigns/$campaignId/taberna'
    | '/_authenticated/campaigns/$campaignId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/spellbook': {
      id: '/_authenticated/spellbook'
      path: '/spellbook'
      fullPath: '/spellbook'
      preLoaderRoute: typeof AuthenticatedSpellbookRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bestiary': {
      id: '/_authenticated/bestiary'
      path: '/bestiary'
      fullPath: '/bestiary'
      preLoaderRoute: typeof AuthenticatedBestiaryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/join/$campaignId': {
      id: '/_authenticated/join/$campaignId'
      path: '/join/$campaignId'
      fullPath: '/join/$campaignId'
      preLoaderRoute: typeof AuthenticatedJoinCampaignIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/characters/new': {
      id: '/_authenticated/characters/new'
      path: '/characters/new'
      fullPath: '/characters/new'
      preLoaderRoute: typeof AuthenticatedCharactersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/characters/$characterId': {
      id: '/_authenticated/characters/$characterId'
      path: '/characters/$characterId'
      fullPath: '/characters/$characterId'
      preLoaderRoute: typeof AuthenticatedCharactersCharacterIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns/new': {
      id: '/_authenticated/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof AuthenticatedCampaignsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns/$campaignId': {
      id: '/_authenticated/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof AuthenticatedCampaignsCampaignIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns/$campaignId/': {
      id: '/_authenticated/campaigns/$campaignId/'
      path: '/'
      fullPath: '/campaigns/$campaignId/'
      preLoaderRoute: typeof AuthenticatedCampaignsCampaignIdIndexRouteImport
      parentRoute: typeof AuthenticatedCampaignsCampaignIdRoute
    }
    '/_authenticated/campaigns/$campaignId/taberna': {
      id: '/_authenticated/campaigns/$campaignId/taberna'
      path: '/taberna'
      fullPath: '/campaigns/$campaignId/taberna'
      preLoaderRoute: typeof AuthenticatedCampaignsCampaignIdTabernaRouteImport
      parentRoute: typeof AuthenticatedCampaignsCampaignIdRoute
    }
    '/_authenticated/campaigns/$campaignId/pnj': {
      id: '/_authenticated/campaigns/$campaignId/pnj'
      path: '/pnj'
      fullPath: '/campaigns/$campaignId/pnj'
      preLoaderRoute: typeof AuthenticatedCampaignsCampaignIdPnjRouteImport
      parentRoute: typeof AuthenticatedCampaignsCampaignIdRoute
    }
    '/_authenticated/campaigns/$campaignId/objetos': {
      id: '/_authenticated/campaigns/$campaignId/objetos'
      path: '/objetos'
      fullPath: '/campaigns/$campaignId/objetos'
      preLoaderRoute: typeof AuthenticatedCampaignsCampaignIdObjetosRouteImport
      parentRoute: typeof AuthenticatedCampaignsCampaignIdRoute
    }
    '/_authenticated/campaigns/$campaignId/mapas': {
      id: '/_authenticated/campaigns/$campaignId/mapas'
      path: '/mapas'
      fullPath: '/campaigns/$campaignId/mapas'
      preLoaderRoute: typeof AuthenticatedCampaignsCampaignIdMapasRouteImport
      parentRoute: typeof AuthenticatedCampaignsCampaignIdRoute
    }
    '/_authenticated/campaigns/$campaignId/lucha': {
      id: '/_authenticated/campaigns/$campaignId/lucha'
      path: '/lucha'
      fullPath: '/campaigns/$campaignId/lucha'
      preLoaderRoute: typeof AuthenticatedCampaignsCampaignIdLuchaRouteImport
      parentRoute: typeof AuthenticatedCampaignsCampaignIdRoute
    }
    '/_authenticated/campaigns/$campaignId/hechizos': {
      id: '/_authenticated/campaigns/$campaignId/hechizos'
      path: '/hechizos'
      fullPath: '/campaigns/$campaignId/hechizos'
      preLoaderRoute: typeof AuthenticatedCampaignsCampaignIdHechizosRouteImport
      parentRoute: typeof AuthenticatedCampaignsCampaignIdRoute
    }
    '/_authenticated/campaigns/$campaignId/habilidades': {
      id: '/_authenticated/campaigns/$campaignId/habilidades'
      path: '/habilidades'
      fullPath: '/campaigns/$campaignId/habilidades'
      preLoaderRoute: typeof AuthenticatedCampaignsCampaignIdHabilidadesRouteImport
      parentRoute: typeof AuthenticatedCampaignsCampaignIdRoute
    }
  }
}

interface AuthenticatedCampaignsCampaignIdRouteChildren {
  AuthenticatedCampaignsCampaignIdHabilidadesRoute: typeof AuthenticatedCampaignsCampaignIdHabilidadesRoute
  AuthenticatedCampaignsCampaignIdHechizosRoute: typeof AuthenticatedCampaignsCampaignIdHechizosRoute
  AuthenticatedCampaignsCampaignIdLuchaRoute: typeof AuthenticatedCampaignsCampaignIdLuchaRoute
  AuthenticatedCampaignsCampaignIdMapasRoute: typeof AuthenticatedCampaignsCampaignIdMapasRoute
  AuthenticatedCampaignsCampaignIdObjetosRoute: typeof AuthenticatedCampaignsCampaignIdObjetosRoute
  AuthenticatedCampaignsCampaignIdPnjRoute: typeof AuthenticatedCampaignsCampaignIdPnjRoute
  AuthenticatedCampaignsCampaignIdTabernaRoute: typeof AuthenticatedCampaignsCampaignIdTabernaRoute
  AuthenticatedCampaignsCampaignIdIndexRoute: typeof AuthenticatedCampaignsCampaignIdIndexRoute
}

const AuthenticatedCampaignsCampaignIdRouteChildren: AuthenticatedCampaignsCampaignIdRouteChildren =
  {
    AuthenticatedCampaignsCampaignIdHabilidadesRoute:
      AuthenticatedCampaignsCampaignIdHabilidadesRoute,
    AuthenticatedCampaignsCampaignIdHechizosRoute:
      AuthenticatedCampaignsCampaignIdHechizosRoute,
    AuthenticatedCampaignsCampaignIdLuchaRoute:
      AuthenticatedCampaignsCampaignIdLuchaRoute,
    AuthenticatedCampaignsCampaignIdMapasRoute:
      AuthenticatedCampaignsCampaignIdMapasRoute,
    AuthenticatedCampaignsCampaignIdObjetosRoute:
      AuthenticatedCampaignsCampaignIdObjetosRoute,
    AuthenticatedCampaignsCampaignIdPnjRoute:
      AuthenticatedCampaignsCampaignIdPnjRoute,
    AuthenticatedCampaignsCampaignIdTabernaRoute:
      AuthenticatedCampaignsCampaignIdTabernaRoute,
    AuthenticatedCampaignsCampaignIdIndexRoute:
      AuthenticatedCampaignsCampaignIdIndexRoute,
  }

const AuthenticatedCampaignsCampaignIdRouteWithChildren =
  AuthenticatedCampaignsCampaignIdRoute._addFileChildren(
    AuthenticatedCampaignsCampaignIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedBestiaryRoute: typeof AuthenticatedBestiaryRoute
  AuthenticatedSpellbookRoute: typeof AuthenticatedSpellbookRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCampaignsCampaignIdRoute: typeof AuthenticatedCampaignsCampaignIdRouteWithChildren
  AuthenticatedCampaignsNewRoute: typeof AuthenticatedCampaignsNewRoute
  AuthenticatedCharactersCharacterIdRoute: typeof AuthenticatedCharactersCharacterIdRoute
  AuthenticatedCharactersNewRoute: typeof AuthenticatedCharactersNewRoute
  AuthenticatedJoinCampaignIdRoute: typeof AuthenticatedJoinCampaignIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBestiaryRoute: AuthenticatedBestiaryRoute,
  AuthenticatedSpellbookRoute: AuthenticatedSpellbookRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCampaignsCampaignIdRoute:
    AuthenticatedCampaignsCampaignIdRouteWithChildren,
  AuthenticatedCampaignsNewRoute: AuthenticatedCampaignsNewRoute,
  AuthenticatedCharactersCharacterIdRoute:
    AuthenticatedCharactersCharacterIdRoute,
  AuthenticatedCharactersNewRoute: AuthenticatedCharactersNewRoute,
  AuthenticatedJoinCampaignIdRoute: AuthenticatedJoinCampaignIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
