ALTER TABLE public.characters
  ADD COLUMN IF NOT EXISTS current_hp INTEGER,
  ADD COLUMN IF NOT EXISTS experience_points INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS armor_class INTEGER,
  ADD COLUMN IF NOT EXISTS conditions TEXT[] NOT NULL DEFAULT '{}';
